import { COLUMNS, normalizeScanRequest, readScanRequest, trimMap } from './request_policy.ts';
function assert(value:unknown){if(!value)throw Error('assertion failed');}
function query(type='stock'){return {columns:COLUMNS,filter:[{left:'type',operation:'equal',right:type},...(type==='stock'?[{left:'is_primary',operation:'equal',right:true}]:[]),{left:'close',operation:'egreater',right:2},{left:'market_cap_basic',operation:'egreater',right:50000000},{left:'exchange',operation:'in_range',right:['AMEX','NASDAQ','NYSE']}],markets:['america'],sort:{sortBy:'market_cap_basic',sortOrder:'desc'},range:[0,8000]};}
Deno.test('stock and ADR requests canonicalize filter ordering',()=>{for(const type of ['stock','dr']){const body=query(type);const a=normalizeScanRequest(body);body.filter.reverse();assert(normalizeScanRequest(body).key===a.key);assert(a.key==='scan:v2:'+(type==='stock'?'stocks':'adrs'));}});
Deno.test('commodity query is accepted',()=>{assert(normalizeScanRequest({columns:COLUMNS,filter:[{left:'name',operation:'in_range',right:['GLD','SLV','COPX','WEAT','CORN','UNG','PALL','PPLT','UGA','USO','CANE','URA']}],markets:['america'],range:[0,20]}).key==='scan:v2:commodities');});
Deno.test('arbitrary ranges, columns and extra fields are rejected',()=>{for(const body of [{...query(),range:[0,99999]},{...query(),columns:['name']},{...query(),extra:'cache flood'},null]){let rejected=false;try{normalizeScanRequest(body);}catch{rejected=true;}assert(rejected);}});
Deno.test('streamed requests are bounded without content-length',async()=>{let rejected=false;try{await readScanRequest(new Request('https://example.test',{method:'POST',body:' '.repeat(17000)}));}catch(e){rejected=e instanceof RangeError;}assert(rejected);});
Deno.test('valid JSON request is accepted and malformed JSON rejected',async()=>{assert((await readScanRequest(new Request('https://example.test',{method:'POST',body:JSON.stringify(query())}))).key==='scan:v2:stocks');let rejected=false;try{await readScanRequest(new Request('https://example.test',{method:'POST',body:'{'}));}catch{rejected=true;}assert(rejected);});
Deno.test('map eviction retains bounded newest entries',()=>{const map=new Map([['a',1],['b',2],['c',3],['d',4]]);trimMap(map,3);assert(map.size===3&&!map.has('a')&&map.has('d'));});
